### ISSUE TITLE
Include leaflet as dependency

### ISSUE THREAD

**Issue by xarsman** [tibiamaps/tibia-map#3]
Is it possible to include `Leaflet` as dependency? This way it's easier to manage the versions..
We could use `bower` or `npm`. It's only for one dependency so maybe it's not worth the setup trouble?

**Comment by mathiasbynens** [comment]
That would be lovely! Some quick notes:

1. We’re already using npm, so no need for Bower.

2. These paths in the build script would have to be changed:

    https://github.com/tibiamaps/tibia-map/blob/1647cb8c1642451e308127de6613438103ad947a/gulpfile.js#L40
    https://github.com/tibiamaps/tibia-map/blob/1647cb8c1642451e308127de6613438103ad947a/gulpfile.js#L27

3. Since the Leaflet beta versions aren’t published on npm, we’ll need to use [Git URLs in `package.json`](https://docs.npmjs.com/files/package.json#git-urls-as-dependencies) for now.
