### ISSUE TITLE
404 error loading tiles that does not exist

### ISSUE THREAD

**Issue by BourbonCrow** [tibiamaps/tibia-map#6]
http://tibiamaps.io/map#31721,32025,7:0

it works totally fine when you load in center of screen (default location) and then move around then it wont try to load files that doesnt exist.. but if you load in off center so you can see a little black.. it will still try to load the 404 files like the link above as an example

**Comment by mathiasbynens** [comment]
This happens because the list of known `*.map` files is being loaded asynchronously.

* Until that list is loaded the map viewer attempts to load every map file it needs. Some 404s may occur if nearby map files don’t exist.
* As soon as the list is loaded, it knows which files don’t exist. No more 404s occur at this point.

Other approaches and why I think they’re bad:

* Loading the list synchronously (i.e. wait until the list is loaded before rendering the map) would slow everything down.
* Hardcoding the list into the `map.js` file would be painful to maintain because the list may change whenever the map data is updated.

IMHO, the few 404s are the lesser evil.
